baseURL = 'https://uy.github.io/'
languageCode = 'en-us'
title = 'Utku Yegen'
theme = 'gokarna'

[params]
  description = "iOS developer by day. “Herbokolog” by night."
  avatarURL = "/images/profil.webp"
  AvatarAltText = "It's me, Utku"
  avatarSize = "size-l"
  showBackToTopButton = true # true or false for "back to top" button on posts
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/yengiyegen"},
    {name = "email", url = "mailto:utkuyegen@gmail.com"}
  ]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    pre = "<span data-feather='briefcase'></span>"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3